#include <gtest/gtest.h>
#include <memory>
#include <string>

#include "board.h"
#include "utils.h"

namespace chess {

// This test suite is designed to verify that creating a board from the
// standard setup function and from its corresponding FEN results in an
// identical board state. Any difference here would cause search inconsistencies.
TEST(BoardSetupTest, StandardVsFen) {
  // 1. Create a board using the standard setup function.
  auto board_from_setup = Board::CreateStandardSetup();

  // 2. Define the FEN string for the standard starting position.
  // This was generated by your engine's `position generate fen` command.
  const std::string start_pos_fen = "R-0,0,0,0-1,1,1,1-1,1,1,1-0,0,0,0-0-x,x,x,yR,yN,yB,yK,yQ,yB,yN,yR,x,x,x/x,x,x,yP,yP,yP,yP,yP,yP,yP,yP,x,x,x/x,x,x,8,x,x,x/bR,bP,10,gP,gR/bN,bP,10,gP,gN/bB,bP,10,gP,gB/bQ,bP,10,gP,gK/bK,bP,10,gP,gQ/bB,bP,10,gP,gB/bN,bP,10,gP,gN/bR,bP,10,gP,gR/x,x,x,8,x,x,x/x,x,x,rP,rP,rP,rP,rP,rP,rP,rP,x,x,x/x,x,x,rR,rN,rB,rQ,rK,rB,rN,rR,x,x,x";

  // 3. Create a second board by parsing the FEN string.
  auto board_from_fen = ParseBoardFromFEN(start_pos_fen);
  ASSERT_NE(board_from_fen, nullptr) << "FEN parsing failed for the start position.";

  // 4. Compare the Zobrist hash keys. This is the most critical check.
  // If this fails, something is different. The following checks will find what.
  ASSERT_EQ(board_from_setup->HashKey(), board_from_fen->HashKey())
    << "Zobrist Hash Keys do not match!";

  // 5. Compare whose turn it is.
  EXPECT_EQ(board_from_setup->GetTurn().GetColor(), board_from_fen->GetTurn().GetColor())
    << "Player turn does not match.";

  // 6. Compare piece placement on every legal square.
  for (int r = 0; r < 14; ++r) {
    for (int c = 0; c < 14; ++c) {
      BoardLocation loc(r, c);
      if (board_from_setup->IsLegalLocation(loc)) {
        Piece piece_setup = board_from_setup->GetPiece(loc);
        Piece piece_fen = board_from_fen->GetPiece(loc);
        EXPECT_EQ(piece_setup, piece_fen) << "Piece mismatch at location " << loc;
      }
    }
  }

  // 7. Compare castling rights for all four players.
  for (int i = 0; i < 4; ++i) {
    PlayerColor color = static_cast<PlayerColor>(i);
    Player player(color);
    const auto& rights_setup = board_from_setup->GetCastlingRights(player);
    const auto& rights_fen = board_from_fen->GetCastlingRights(player);
    EXPECT_EQ(rights_setup.Kingside(), rights_fen.Kingside())
      << "Kingside castling rights mismatch for color " << i;
    EXPECT_EQ(rights_setup.Queenside(), rights_fen.Queenside())
      << "Queenside castling rights mismatch for color " << i;
  }

  // NOTE: En Passant info is not included in the startpos FEN, so both boards
  // should have no en passant targets. This check confirms that.
  // To make this testable, we need a public getter for en_passant_target_.
  // (See Step 2 below for the change to board.h)
  for (int i = 0; i < 4; ++i) {
    PlayerColor color = static_cast<PlayerColor>(i);
    EXPECT_FALSE(board_from_setup->GetEnPassantTarget(color).Present())
      << "En passant target should be absent for setup board, color " << i;
    EXPECT_FALSE(board_from_fen->GetEnPassantTarget(color).Present())
      << "En passant target should be absent for FEN board, color " << i;
  }
}

}  // namespace chess